version: '3.9'

services:
  # Working NodeJS service
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: sh -c "npm run dev-run" # run server in dev mode.
#    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run dev-run" # run server in dev mode after install dependencies.
#    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run check-bytecode" # Check app bytecode in console.
#    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run check-gc" # Check result Garbage Collector in console
#    tty: true
    restart: 'always'
    volumes:
      - ./app/basics:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

  # Command line for install, check
  node-cli:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    restart: 'no'
    volumes:
#      - ./app/basics:/app
      - ./app/weatherCLI:/app
    environment:
      PORT: 3000

  # weather cli
  node-weather-cli:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: sh -c "npm start" # run server cli.
    restart: 'no'
    volumes:
      - ./app/weatherCLI:/app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
