FROM node:17-alpine

RUN npm i -g npm@latest typescript

# clinic: Diagnose performance issues in your Node.js applications
# autocannon: benchmarking tool
#RUN npm i -g clinic autocannon

WORKDIR /app
